name = "ToolCallFormat"
uuid = "ae3acb55-b8cb-46d1-89eb-5b4f98bcbe10"
authors = ["Cvikli <havlikmarcell@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
